mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/im?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
oss:
  Endpoint: "oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5tNCXPJwS3MstKoKgixh"
  AccessKeySecret: "YhHE8OyCMsqfjwOnxQ1oO7paYlDjVHX"
  Bucket : "ginchat"

timeout:
  DelayHeartbeat: 3000000000000   #延迟心跳时间  单位秒
  HeartbeatHz: 3000000000000   #每隔多少秒心跳时间
  HeartbeatMaxTime: 3000000000000  #最大心跳时间  ，超过此就下线
  RedisOnlineTime: 3000000000000  #缓存的在线用户时长   单位H

port:
  server: ":7080"  # 修改为7080端口
  udp: 3001
txemail:
  from: "3090497217@qq.com"
  to: "3090497217@qq.com"
  password: "wocugzbyzvisddee"

